name: calibre
base: core22
adopt-info: calibre
grade: stable
summary: Powerful and Advanced E-Book Reader.
description: |
  Powerful and Advanced E-Book Reader and Editor, written in python and qt.
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
    build-for: amd64
    
layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET/espeak-ng-data:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/espeak-ng-data

slots:
  calibre:
    interface: dbus
    bus: session
    name: com.calibre_ebook.calibre
    
apps:
  calibre:
    command: bin/calibre
    extensions:
      - kde-neon
    plugs:
      - home
      - audio-playback
      - bluez
      - network
      - network-bind
      - network-status
      - optical-drive
      - removable-media
      - udisks2
      - unity7
      - screen-inhibit-control
      - mount-observe
      - browser-support
    common-id: com.calibre_ebook.calibre 
    desktop: share/applications/calibre.desktop
      
  ebook-viewer:
    command: bin/ebook-viewer
    extensions:
      - kde-neon
    plugs:
      - home
      - removable-media
      - audio-playback
      - network
      - network-status
      - bluez
      - optical-drive
      - unity7
      - screen-inhibit-control
      
  ebook-edit:
    command: bin/ebook-edit
    extensions:
      - kde-neon
    plugs:
      - home
      - removable-media
      - network
      - network-status
      - bluez
      - optical-drive
      - unity7
      - screen-inhibit-control    
      
  lrf-viewer:
    command: bin/lrf-viewer
    extensions:
      - kde-neon
    plugs:
      - home
      - removable-media
      - network
      - network-status
      - bluez
      - optical-drive
      - unity7
      - screen-inhibit-control
      
parts:
  calibre:
    source: https://github.com/kovidgoyal/calibre.git
    plugin: dump
    build-packages:  
      - build-essential
      - curl
      - bash-completion
      - tar
      - wget
      - p7zip-full
      - qt6-base-dev
      - qt6-base-dev-tools
      - qt6-multimedia-dev
      - qt6-image-formats-plugins
      - qt6-l10n-tools
      - python3-pyqt5.qtwebkit
      - qt6-webengine-dev
      - qt6-webengine-dev-tools
      - qt6-webview-plugins
      - qt6-webview-dev
      - qt6-tools-dev
      - xdg-utils
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0 | cut -c 2-)
      VER="$(git describe --tags --abbrev=0 | cut -c 2-)"
      curl -LO https://github.com/kovidgoyal/calibre/releases/download/v${VER}/calibre-${VER}-x86_64.txz
    override-build : |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/lib/calibre/
      mkdir -p $CRAFT_PART_INSTALL/bin $CRAFT_PART_INSTALL/share/{applications,desktop-directories,icons/hicolor,mime/packages}
      tar -xvf calibre*.txz -C $CRAFT_PART_INSTALL/lib/calibre
      $CRAFT_PART_INSTALL/lib/calibre/calibre_postinstall =$CRAFT_PART_INSTALL
 
  tts:
    plugin: nil
    stage-packages:
      - espeak-ng
      - speech-dispatcher-espeak-ng
      - libaudio2
      - libsndio7.0
  
  fatloss:
    plugin: nil
    after: [calibre, tts]
    override-prime: |
      craftctl default
      rm -f calibre*.txz
      rm -f Changelog*.txt
      rm ./lib/calibre/resources/fonts/liberation/*.ttf
      
  cleanup:
    after: [calibre, fatloss, tts]
    plugin: nil
    build-snaps: [core22, kde-frameworks-5-102-qt-5-15-8-core22, kde-frameworks-5-102-qt-5-15-8-core22-sd, gtk-common-themes]
    override-prime: |
      set -eux
      for snap in "core22" "gtk-common-themes" "kde-frameworks-5-102-qt-5-15-8-core22" "kde-frameworks-5-102-qt-5-15-8-core22-sd" ; do
        cd "/snap/$snap/current" && find . -type f,l -name *.so.* -exec rm -f "$CRAFT_PRIME/{}" \;
      done    
