name: calibre
base: core22
adopt-info: calibre
grade: stable
summary: Powerful and Advanced E-Book Reader.
description: |
  Powerful and Advanced E-Book Reader and Editor, written in python and qt.
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
    build-for: amd64
layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET/espeak-ng-data:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/espeak-ng-data

slots:
  calibre:
    interface: dbus
    bus: session
    name: com.calibre_ebook.calibre
    
apps:
  calibre:
    command: bin/calibre
    extensions:
      - kde-neon
    plugs:
      - home
      - audio-playback
      - network
      - bluez
      - network-status
      - optical-drive
      - removable-media
    common-id: com.calibre_ebook.calibre 
    desktop: share/applications/com.calibre_ebook.calibre.desktop
  
  ebook-editor:
    command: bin/ebook-edit
    plugs:
      - home
      - removable-media
      - network
  ebook-viewer:
    command: bin/ebook-viewer
    plugs:
      - home
      - removable-media
      - optical-drive
      - network
      - audio-playback
   
  lrf-viewer:
    command: bin/lrfviewer
    plugs: 
      - home
      - network
      - removable-media
      
parts:
  calibre:
    source: https://github.com/kovidgoyal/calibre.git
    parse-info: [/share/metainfo/com.calibre_ebook.calibre.metainfo.xml]
    plugin: dump
    build-packages:  
      - build-essential
      - curl
      - bash-completion
      - libfreetype6
      - libfreetype6-dev
      - libfreetype-dev
      - tar
      - wget
      - p7zip-full
      - qt6-base-dev
      - qt6-base-dev-tools
      - qt6-multimedia-dev
      - qt6-image-formats-plugins
      - qt6-l10n-tools
      - xdg-utils
      - python3-pyqt5.qtwebkit
      - qt6-webengine-dev
      - qt6-webengine-dev-tools
      - qt6-webview-plugins
      - qt6-webview-dev
      - qt6-tools-dev
      - hicolor-icon-theme
      - libqt5xdg3
      - python3-xdg
      - qtxdg-dev-tools
      - xdg-desktop-portal
      - xdg-desktop-portal-gtk
      - xdg-user-dirs
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0 | cut -c 2-)
      VER="$(git describe --tags --abbrev=0 | cut -c 2-)"
      curl -LO https://github.com/kovidgoyal/calibre/releases/download/v${VER}/calibre-${VER}-x86_64.txz
      mkdir -p /usr/share/desktop-directories/
    override-build : |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/lib/calibre
      mkdir -p "${CRAFT_PART_INSTALL}/bin" "${CRAFT_PART_INSTALL}"/share/{applications,desktop-directories,icons/hicolor,mime/packages}
      tar -xvf calibre*.txz -C "${CRAFT_PART_INSTALL}/lib/calibre"
      rm -f calibre*.txz
      $CRAFT_PART_INSTALL/lib/calibre/calibre_postinstall --root=$CRAFT_PART_INSTALL
  tts:
    plugin: nil
    stage-packages:
      - espeak-ng
      - speech-dispatcher-espeak-ng
      - libaudio2
      - libsndio7.0
