name: calibre
base: core22
adopt-info: calibre
grade: stable
summary: Powerful and Advanced E-Book Reader.
description: |
  Powerful and Advanced E-Book Reader and Editor, written in python and qt.
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
    build-for: amd64
layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET/espeak-ng-data:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/espeak-ng-data

slots:
  calibre:
    interface: dbus
    bus: session
    name: com.calibre_ebook.calibre
    
apps:
  calibre:
    command: opt/calibre/calibre
    extensions:
      - kde-neon
    plugs:
      - home
      - raw-usb
      - network
      - network-status
      - optical-drive
      - removable-media
    common-id: com.calibre_ebook.calibre
    desktop: usr/share/applications/calibre-gui.desktop
    
parts:
  calibre:
    source: https://github.com/kovidgoyal/calibre.git
    plugin: dump
    build-snaps:
      - kf5-5-105-qt-5-15-9-core22-sdk
    build-packages:
      - build-essential
      - curl
      - bash-completion
      - libfreetype6
      - libfreetype6-dev
      - libfreetype-dev
      - tar
      - wget
      - p7zip-full
      - qt6-base-dev
      - qt6-base-dev-tools
      - qt6-multimedia-dev
      - qt6-image-formats-plugins
      - qt6-l10n-tools
      - xdg-utils
      - python3-pyqt5.qtwebkit
      - qt6-webengine-dev
      - qt6-webengine-dev-tools
      - qt6-webview-plugins
      - qt6-webview-dev
      - qt6-tools-dev
      - hicolor-icon-theme
      - libqt5xdg3
      - python3-xdg
      - qtxdg-dev-tools
      - xdg-desktop-portal
      - xdg-desktop-portal-gtk
      - xdg-user-dirs
      
    override-pull: |
      craftctl default
      mkdir -p /opt/calibre && rm -rf /opt/calibre/*
      mkdir /usr/share/desktop-directories/
      craftctl set version=$(git describe --tags --abbrev=0)
      VER="$(git describe --tags --abbrev=0)"
      wget -q -O- https://github.com/kovidgoyal/calibre/releases/download/${VER}/calibre-${VER}-x86_64.txz |\
           tar xvf -C /opt/calibre 
    
    override-build: |
      craftctl default 
      /opt/calibre/calibre_postinstall
    
  tts:
    plugin: nil
    stage-packages:
      - espeak-ng
      - speech-dispatcher-espeak-ng
      - libaudio2
      - libsndio7.0
