name: calibre
base: core22
adopt-info: calibre
grade: stable
summary: Powerful and Advanced E-Book Reader.
description: |
  Powerful and Advanced E-Book Reader and Editor, written in python and qt.
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
    build-for: amd64
    
layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET/espeak-ng-data:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/espeak-ng-data

slots:
  calibre:
    interface: dbus
    bus: session
    name: com.calibre_ebook.calibre
    
apps:
  calibre:
    command: opt/calibre/calibre
    #command: usr/bin/calibre
    extensions:
      - kde-neon
    plugs:
      - home
      - audio-playback
      - bluez
      - network
      - network-bind
      - network-status
      - optical-drive
      - removable-media
      - udisks2
      - unity7
      - screen-inhibit-control
      - mount-observe
      - browser-support
    common-id: com.calibre_ebook.calibre 
    #desktop: usr/share/applications/calibre.desktop
      
parts:
  calibre:
    source: https://github.com/kovidgoyal/calibre.git
    plugin: dump
    build-packages:  
      - build-essential
      - curl
      - bash-completion
      - libfreetype6
      - libfreetype6-dev
      - libfreetype-dev
      - tar
      - wget
      - p7zip-full
      - qt6-base-dev
      - qt6-base-dev-tools
      - qt6-multimedia-dev
      - qt6-image-formats-plugins
      - qt6-l10n-tools
      - xdg-utils
      - python3-pyqt5.qtwebkit
      - qt6-webengine-dev
      - qt6-webengine-dev-tools
      - qt6-webview-plugins
      - qt6-webview-dev
      - qt6-tools-dev
      - hicolor-icon-theme
      - libqt5xdg3
      - python3-xdg
      - qtxdg-dev-tools
      - xdg-desktop-portal
      - xdg-desktop-portal-gtk
      - xdg-user-dirs
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0 | cut -c 2-)
      VER="$(git describe --tags --abbrev=0 | cut -c 2-)"
      curl -LO https://github.com/kovidgoyal/calibre/releases/download/v${VER}/calibre-${VER}-x86_64.txz
      mkdir -p $CRAFT_PART_SRC/opt/calibre/
      mkdir -p /usr/share/desktop-directories/
      rm -rf $CRAFT_PART_SRC/opt/calibre/*
      # mkdir -p /usr/share/desktop-directories/ may be the root cause of all errors as it leads to 
      # calibre not adjusting to the snap build env,this should be : mkdir -p $CRAFT_PART_SRC/usr/share/desktop-directories/
      # But without it XDG Gives error and halts build, using it with
      # $CRAFT_PART_SRC leads to XDG Not recognising it
      tar -xvf calibre*.txz -C $CRAFT_PART_SRC/opt/calibre
    
    #override-build : |
      #craftctl default
      #$CRAFT_PART_INSTALL/opt/calibre/calibre_postinstall
      
  tts:
    plugin: nil
    stage-packages:
      - espeak-ng
      - speech-dispatcher-espeak-ng
      - libaudio2
      - libsndio7.0
  
  fatloss:
    plugin: nil
    after: [calibre, tts]
    override-prime: |
      craftctl default
      rm -f calibre*.txz
      rm -f Changelog*.txt
      
  cleanup:
    after: [calibre, fatloss, tts]
    plugin: nil
    build-snaps: [core22, kde-frameworks-5-102-qt-5-15-8-core22, kde-frameworks-5-102-qt-5-15-8-core22-sd, gtk-common-themes]
    override-prime: |
      set -eux
      for snap in "core22" "gtk-common-themes" "kde-frameworks-5-102-qt-5-15-8-core22" "kde-frameworks-5-102-qt-5-15-8-core22-sd" ; do
        cd "/snap/$snap/current" && find . -type f,l -name *.so.* -exec rm -f "$CRAFT_PRIME/{}" \;
      done    
