name: calibre-qt
base: core22
adopt-info: calibre-qt
summary: The One Stop Solution To Your Ebook Needs
description: |
  calibre is a powerful and easy to use e-book manager.It’s also completely free and open source. 
grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64
    build-for: amd64

plugs: 

apps:
  calibre-qt:
    command: opt/calibre/bin/calibre
    extensions:
      - kde-neon 
    environment:
            GTK_USE_PORTAL: 1
    plugs:
      - home
      - audio-playback
      - network-status
      - network
      - network-bind
      - raw-usb
      - optical-drive
      - removable-media
      - unity7
      - screen-inhibit-control
      
parts:
  calibre-qt:
    source: https://github.com/kovidgoyal/calibre.git
    plugin: nil
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0)
      curl -LO https://github.com/kovidgoyal/calibre/releases/download/v6.15.1/calibre-6.15.1-x86_64.txz
      mkdir -p /opt/calibre && rm -rf /opt/calibre/* 
      tar xvf calibre-6.15.1-x86_64.txz -C /opt/calibre && /opt/calibre/calibre_postinstall
      
    build-snaps:
      - kf5-5-104-qt-5-15-8-core22-sdk
   
    build-packages:
      - wget
      - curl
      - build-essential
      - tar
     
    
      
      
      
